-- Generated by chromix from a matugen template. Changes are lost on the
-- next theme switch.

hl.config({
  general = {
    col = {
      active_border = "rgba({{colors.primary.default.hex_stripped}}ee)",
      inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}aa)",
    },
  },
  decoration = {
    shadow = {
      -- M3's shadow role is plain black; a deep tone of the muted
      -- secondary hue keeps the shadow tinted to the theme, and holds
      -- the same in light and dark.
      color = "rgba({{colors.on_secondary_fixed.default.hex_stripped}}ee)",
    },
  },
})
