-- Generated by chromix from a matugen template. Changes are lost on the
-- next theme switch.

hl.config({
  general = {
    col = {
      active_border = "rgba({{colors.primary.default.hex_stripped}}ee)",
      inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}aa)",
    },
  },
  decoration = {
    shadow = {
      color = "rgba({{colors.shadow.default.hex_stripped}}ee)",
    },
  },
})
