-- Generated by chromix from a matugen template. Changes are lost on the
-- next theme switch.
--
-- Needs mini.base16: with vim.pack, add
--   vim.pack.add({ "https://github.com/nvim-mini/mini.base16" })
-- before loading this file.

local ok, base16 = pcall(require, "mini.base16")
if not ok then
  vim.notify("chromix: mini.base16 is not installed", vim.log.levels.WARN)
  return
end

vim.o.background = "{{mode}}"

-- base00-07 are the surface ramp, so the editor sits on the same
-- colours as the shell. The accents map M3's primary and tertiary onto
-- functions and constants, and take the fixed hues for the rest so
-- errors stay red and strings stay green.
base16.setup({
  palette = {
    base00 = "{{colors.surface.default.hex}}",
    base01 = "{{colors.surface_container.default.hex}}",
    base02 = "{{colors.surface_container_highest.default.hex}}",
    base03 = "{{colors.outline.default.hex}}",
    base04 = "{{colors.on_surface_variant.default.hex}}",
    base05 = "{{colors.on_surface.default.hex}}",
    base06 = "{{colors.on_surface.default.hex}}",
    base07 = "{{colors.on_primary_container.default.hex}}",
    base08 = "{{colors.red.default.hex}}",
    base09 = "{{colors.tertiary.default.hex}}",
    base0A = "{{colors.yellow.default.hex}}",
    base0B = "{{colors.green.default.hex}}",
    base0C = "{{colors.cyan.default.hex}}",
    base0D = "{{colors.primary.default.hex}}",
    base0E = "{{colors.magenta.default.hex}}",
    base0F = "{{colors.secondary.default.hex}}",
  },
})

vim.g.colors_name = "chromix"
