" Generated by chromix from a matugen template. Changes are lost on the
" next theme switch.
"
" The neovim target's base16 palette for plain vim: the surface roles
" from the page to the text, the fixed hues for syntax, and the seed's
" roles for the selection, cursor line number and status line.

hi clear
if exists('syntax_on')
  syntax reset
endif
set background={{mode}}
if has('termguicolors')
  set termguicolors
endif
let g:colors_name = 'chromix'

let s:base00 = '{{colors.surface_container_high.default.hex}}'
let s:base01 = '<* if {{ is_dark_mode }} *>{{colors.surface_container_highest.default.hex}}<* else *>{{colors.surface_dim.default.hex}}<* endif *>'
let s:base02 = '{{colors.outline_variant.default.hex}}'
let s:base03 = '{{colors.outline.default.hex}}'
let s:base04 = '{{colors.on_surface_variant.default.hex}}'
let s:base05 = '{{colors.on_surface.default.hex}}'
let s:base08 = '{{colors.red.default.hex}}'
let s:base09 = '{{colors.orange.default.hex}}'
let s:base0A = '{{colors.yellow.default.hex}}'
let s:base0B = '{{colors.green.default.hex}}'
let s:base0C = '{{colors.cyan.default.hex}}'
let s:base0D = '{{colors.blue.default.hex}}'
let s:base0E = '{{colors.magenta.default.hex}}'

function! s:hi(group, fg, bg, attr) abort
  execute 'hi' a:group
        \ 'guifg=' . (a:fg ==# '' ? 'NONE' : a:fg)
        \ 'guibg=' . (a:bg ==# '' ? 'NONE' : a:bg)
        \ 'gui=' . (a:attr ==# '' ? 'NONE' : a:attr)
        \ 'cterm=' . (a:attr ==# '' ? 'NONE' : a:attr)
endfunction

" Editor
call s:hi('Normal', s:base05, s:base00, '')
call s:hi('NonText', s:base02, '', '')
call s:hi('EndOfBuffer', s:base02, '', '')
call s:hi('SpecialKey', s:base03, '', '')
call s:hi('LineNr', s:base03, s:base00, '')
call s:hi('CursorLine', '', s:base01, '')
call s:hi('CursorColumn', '', s:base01, '')
call s:hi('ColorColumn', '', s:base01, '')
call s:hi('CursorLineNr', '{{colors.primary.default.hex}}', s:base01, 'bold')
call s:hi('SignColumn', s:base03, s:base00, '')
call s:hi('FoldColumn', s:base03, s:base00, '')
call s:hi('Folded', s:base04, s:base01, '')
call s:hi('VertSplit', s:base02, '', '')
call s:hi('WinSeparator', s:base02, '', '')
call s:hi('Visual', '{{colors.on_primary_container.default.hex}}', '{{colors.primary_container.default.hex}}', '')
call s:hi('Search', '{{colors.on_tertiary_container.default.hex}}', '{{colors.tertiary_container.default.hex}}', '')
call s:hi('IncSearch', '{{colors.on_tertiary.default.hex}}', '{{colors.tertiary.default.hex}}', '')
call s:hi('CurSearch', '{{colors.on_tertiary.default.hex}}', '{{colors.tertiary.default.hex}}', '')
call s:hi('MatchParen', '', s:base02, 'bold')
call s:hi('StatusLine', '{{colors.on_secondary_container.default.hex}}', '{{colors.secondary_container.default.hex}}', '')
call s:hi('StatusLineNC', s:base04, s:base01, '')
call s:hi('StatusLineTerm', '{{colors.on_secondary_container.default.hex}}', '{{colors.secondary_container.default.hex}}', '')
call s:hi('StatusLineTermNC', s:base04, s:base01, '')
call s:hi('TabLine', s:base04, s:base01, '')
call s:hi('TabLineFill', '', s:base01, '')
call s:hi('TabLineSel', '{{colors.on_primary.default.hex}}', '{{colors.primary.default.hex}}', '')
call s:hi('Pmenu', s:base05, s:base01, '')
call s:hi('PmenuSel', '{{colors.on_primary_container.default.hex}}', '{{colors.primary_container.default.hex}}', '')
call s:hi('PmenuSbar', '', s:base01, '')
call s:hi('PmenuThumb', '', s:base03, '')
call s:hi('WildMenu', '{{colors.on_primary_container.default.hex}}', '{{colors.primary_container.default.hex}}', '')
call s:hi('Directory', s:base0D, '', '')
call s:hi('Title', s:base0D, '', 'bold')
call s:hi('Question', s:base0B, '', '')
call s:hi('MoreMsg', s:base0B, '', '')
call s:hi('ModeMsg', s:base0B, '', '')
call s:hi('WarningMsg', '{{colors.warning.default.hex}}', '', '')
call s:hi('ErrorMsg', '{{colors.error.default.hex}}', '', 'bold')
call s:hi('Error', '{{colors.on_error_container.default.hex}}', '{{colors.error_container.default.hex}}', '')
call s:hi('Todo', s:base0A, s:base01, 'bold')
call s:hi('SpellBad', '', '', 'undercurl')
call s:hi('SpellCap', '', '', 'undercurl')
call s:hi('Conceal', s:base03, '', '')

" Diffs
call s:hi('DiffAdd', s:base0B, s:base01, '')
call s:hi('DiffChange', s:base0A, s:base01, '')
call s:hi('DiffDelete', s:base08, s:base01, '')
call s:hi('DiffText', s:base0D, s:base01, 'bold')
call s:hi('diffAdded', s:base0B, '', '')
call s:hi('diffRemoved', s:base08, '', '')
call s:hi('diffChanged', s:base0A, '', '')
call s:hi('diffLine', s:base0C, '', '')

" Syntax, by the base16 slots
call s:hi('Comment', s:base03, '', 'italic')
call s:hi('Constant', s:base09, '', '')
call s:hi('String', s:base0B, '', '')
call s:hi('Character', s:base08, '', '')
call s:hi('Number', s:base09, '', '')
call s:hi('Boolean', s:base09, '', '')
call s:hi('Float', s:base09, '', '')
call s:hi('Identifier', s:base08, '', '')
call s:hi('Function', s:base0D, '', '')
call s:hi('Statement', s:base0E, '', '')
call s:hi('Conditional', s:base0E, '', '')
call s:hi('Repeat', s:base0E, '', '')
call s:hi('Label', s:base0A, '', '')
call s:hi('Operator', s:base05, '', '')
call s:hi('Keyword', s:base0E, '', '')
call s:hi('Exception', s:base08, '', '')
call s:hi('PreProc', s:base0A, '', '')
call s:hi('Include', s:base0D, '', '')
call s:hi('Define', s:base0E, '', '')
call s:hi('Macro', s:base08, '', '')
call s:hi('Type', s:base0A, '', '')
call s:hi('StorageClass', s:base0A, '', '')
call s:hi('Structure', s:base0E, '', '')
call s:hi('Typedef', s:base0A, '', '')
call s:hi('Special', s:base0C, '', '')
call s:hi('SpecialChar', s:base0C, '', '')
call s:hi('Tag', s:base0A, '', '')
call s:hi('Delimiter', s:base04, '', '')
call s:hi('Underlined', s:base0D, '', 'underline')
call s:hi('Ignore', s:base03, '', '')

delfunction s:hi
